INSERT INTO "public"."directorate" ("name") VALUES
('AYUDANTIA POLICIAL');
INSERT INTO "public"."directorate" ("name") VALUES
('DIRECCION ADMINISTRACION');
INSERT INTO "public"."directorate" ("name") VALUES
('DIRECCION ASUNTOS JURIDICOS');
INSERT INTO "public"."directorate" ("name") VALUES
('DIRECCION BENEFICIARIOS'),
('DIRECCION DE CONTROL Y PREVENCION'),
('DIRECCION DE INFORMATICA Y SISTEMAS'),
('DIRECCION DE RECURSOS HUMANOS'),
('DIRECCION GENERAL DE OPERACIONES'),
('PRESIDENCIA'),
('SECRETARIA GENERAL'),
('UNIDAD DE AUDITORIA INTERNA');